name: Test the package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-22.04
    env:
      TEST_FLAG: --no-default-features --features systemd_249,unified_cgroup
    steps:
      - name: Prepare
        run: chmod 755 $HOME
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test systemd-run lib
        run: sudo su --login $(whoami) -c "cd $PWD; cargo test $TEST_FLAG"
      - name: Test systemd-run lib as Root
        run: sudo su --login $(whoami) -c "cd $PWD; CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER=sudo cargo test $TEST_FLAG -- --include-ignored root"
      - name: Debug
        if: always()
        run: journalctl -b
